import React from 'react'


let Api = [{
    id: 1,
    image: "./img/room1.jpg",
    image1: "./img/room2.jpg",
    image2: "./img/room3.jpg",
    tittle: "Ritz-Carlton",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to ritz this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "425/-",
    btn: "go Next",
}, {
    id: 2,
    image: "./img/room2.jpg",
    image1: "./img/room5.jpg",
    image2: "./img/room6.jpg",
    tittle: "Peninsula Chicago",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to peninsual this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "420/-",
    btn: "go Next",
}, {
    id: 3,
    image: "./img/room3.jpg",
    image1: "./img/room9.jpg",
    image2: "./img/room11.jpg",
    tittle: "Belmond",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to belond this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "400/-",
    btn: "go Next",
}, {
    id: 4,
    image: "./img/room4.jpg",
    image1: "./img/room8.jpg",
    image2: "./img/room12.jpg",
    tittle: "Fort Harrison",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to fort this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "395/-",
    btn: "go Next",
}, {
    id: 5,
    image: "./img/room5.jpg",
    image1: "./img/room1.jpg",
    image2: "./img/room2.jpg",
    tittle: "Hollywood Plaza",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to hollywood this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "350/-",
    btn: "go Next",
}, {
    id: 6,
    image: "./img/room6.jpg",
    image1: "./img/room5.jpg",
    image2: "./img/room10.jpg",
    tittle: "Antlers Hilton",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to antlers this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "450/-",
    btn: "go Next",
}, {
    id: 7,
    image: "./img/room7.jpg",
    image1: "./img/room8.jpg",
    image2: "./img/room2.jpg",
    tittle: "DuPont Plaza",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to dupont this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "409/-",
    btn: "go Next",
}, {
    id: 8,
    image: "./img/room8.jpg",
    image1: "./img/room3.jpg",
    image2: "./img/room4.jpg",
    tittle: "Yosemite Lodge",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to yosemite this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "407/-",
    btn: "go Next",
}, {
    id: 9,
    image: "./img/room9.jpg",
    image1: "./img/room12.jpg",
    image2: "./img/room11.jpg",
    tittle: "Ritz Plaza",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to ritz this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "390/-",
    btn: "go Next",
}, {
    id: 10,
    image: "./img/room10.jpg",
    image1: "./img/room9.jpg",
    image2: "./img/room6.jpg",
    tittle: "Waldorf Astoria",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to waldorf this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "440/-",
    btn: "go Next",
}, {
    id: 11,
    image: "./img/room11.jpg",
    image1: "./img/room4.jpg",
    image2: "./img/room8.jpg",
    tittle: "Rancho Casino",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to rancho this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "490/-",
    btn: "go Next",
}, {
    id: 12,
    image: "./img/room1.jpg",
    image1: "./img/room5.jpg",
    image2: "./img/room10.jpg",
    tittle: "Mandarin Oriental",
    para: "few quick example text to build on the card title and make up the bulk of the card's content.",
    summery: "it belong to mandarin this is dummi data Lorem ipsum, dolor sit amet consectetur adipisicing elit. Libero porro qui dolore commodi nulla numquam, reiciendis fuga quod animi delectus maxime harum eveniet explicabo. Nulla, tempora ad! Eius, aperiam earum.phone pay +google pay+paytm=000000000 & upi=00@pytm",
    price: "482/-",
    btn: "go Next",
}
]
export default Api;